{% set python_min = '3.11' %}
{% set name = "s1_frame_enumerator" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/s1_frame_enumerator-{{ version }}.tar.gz
  sha256: fae50274cfffdb6e350db2d3adbabde8c251b99623225fc283d6e0327e1b3397

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=60
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    - geopandas
    - rasterio
    - asf_search
    - tqdm
    - requests
    - shapely >=2.0

test:
  imports:
    - s1_frame_enumerator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ACCESS-Cloud-Based-InSAR/s1_frame_enumerator
  summary: Enumerate interferogram pairs from ARIA spatially fixed frames
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cmarshak
    - jhkennedy
